
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwputiwhygpjbmswmolo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cHV0aXdoeWdwamJtc3dtb2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzUzODYsImV4cCI6MjA2MDgxMTM4Nn0.tdvPutga1jVMiYyUx-3AtAc7EvO2AJE-Hxj-vhhsBHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
